"""Add persona and team config tables

Revision ID: 092e38fc9485
Revises: 499a4689c985
Create Date: 2026-07-26 18:27:31.900790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '092e38fc9485'
down_revision: Union[str, None] = '499a4689c985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_personas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('prompt_template', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_personas_role_type'), 'system_personas', ['role_type'], unique=False)
    op.create_table('user_team_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('market_agent_ids', sa.JSON(), nullable=True),
    sa.Column('decision_agent_ids', sa.JSON(), nullable=True),
    sa.Column('arbitrator_agent_id', sa.String(), nullable=True),
    sa.Column('risk_agent_id', sa.String(), nullable=True),
    sa.Column('execution_agent_id', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_index(op.f('idx_onchain_wallet_events_published_at'), table_name='onchain_wallet_events')
    op.drop_index(op.f('idx_onchain_wallet_events_source'), table_name='onchain_wallet_events')
    op.drop_table('onchain_wallet_events')
    op.drop_index(op.f('idx_news_interp_asset_clusters_gin'), table_name='news_interpretations', postgresql_using='gin')
    op.drop_index(op.f('idx_news_interp_assets_gin'), table_name='news_interpretations', postgresql_using='gin')
    op.drop_index(op.f('idx_news_interp_factor_tags_gin'), table_name='news_interpretations', postgresql_using='gin')
    op.drop_index(op.f('idx_news_interp_final_status_time'), table_name='news_interpretations')
    op.drop_index(op.f('idx_news_interp_interpreted_at'), table_name='news_interpretations')
    op.drop_index(op.f('idx_news_interp_severity_time'), table_name='news_interpretations')
    op.drop_index(op.f('idx_news_interp_status_retry'), table_name='news_interpretations')
    op.drop_table('news_interpretations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_interpretations',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('language', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_tier', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bias', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('magnitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('severity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_type_l1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_type_l2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary_cn', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assets', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('asset_clusters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('factor_tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('impact_tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('mapping_version', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cross_market_impacts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('evidence_quotes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('final_status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('interpret_status', sa.TEXT(), server_default=sa.text("'NEW'::text"), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('next_retry_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('interpreted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('interpreter_version', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_fingerprint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fingerprint_algo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fingerprint_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reinterpret_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_reinterpret_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('noise_flags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('news_interpretations_pkey')),
    sa.UniqueConstraint('news_id', name=op.f('news_interpretations_news_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_news_interp_status_retry'), 'news_interpretations', ['interpret_status', 'next_retry_at'], unique=False)
    op.create_index(op.f('idx_news_interp_severity_time'), 'news_interpretations', ['severity', sa.literal_column('interpreted_at DESC')], unique=False)
    op.create_index(op.f('idx_news_interp_interpreted_at'), 'news_interpretations', [sa.literal_column('interpreted_at DESC')], unique=False)
    op.create_index(op.f('idx_news_interp_final_status_time'), 'news_interpretations', ['final_status', sa.literal_column('interpreted_at DESC')], unique=False)
    op.create_index(op.f('idx_news_interp_factor_tags_gin'), 'news_interpretations', ['factor_tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_news_interp_assets_gin'), 'news_interpretations', ['assets'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_news_interp_asset_clusters_gin'), 'news_interpretations', ['asset_clusters'], unique=False, postgresql_using='gin')
    op.create_table('onchain_wallet_events',
    sa.Column('event_uid', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_news_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('chain', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tx_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wallet_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('counterparty_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('direction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('asset_symbol', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amount_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_payload', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('event_uid', name=op.f('onchain_wallet_events_pkey'))
    )
    op.create_index(op.f('idx_onchain_wallet_events_source'), 'onchain_wallet_events', ['source'], unique=False)
    op.create_index(op.f('idx_onchain_wallet_events_published_at'), 'onchain_wallet_events', ['published_at'], unique=False)
    op.drop_table('user_team_configs')
    op.drop_index(op.f('ix_system_personas_role_type'), table_name='system_personas')
    op.drop_table('system_personas')
    # ### end Alembic commands ###
