"""baseline_schema_20260320

Revision ID: 20260320base
Revises:
Create Date: 2026-03-20 14:36:36.571596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260320base'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_macro_metric_time', 'macro_metrics', ['metric_name', 'timestamp'], unique=False)
    op.create_index(op.f('ix_macro_metrics_timestamp'), 'macro_metrics', ['timestamp'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('onchain_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_onchain_metric_time', 'onchain_metrics', ['symbol', 'metric_name', 'timestamp'], unique=False)
    op.create_index(op.f('ix_onchain_metrics_timestamp'), 'onchain_metrics', ['timestamp'], unique=False)
    op.create_table('paper_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('daily_start_balance', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('high_watermark', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('lock_reason', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_configs',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('wallet_address', sa.String(), nullable=True),
    sa.Column('nonce', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    op.create_table('workflow_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='workflowstatus'), nullable=True),
    sa.Column('start_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=True),
    sa.Column('periodic_review_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('log_type', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('artifact', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['workflow_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_id'), 'agent_logs', ['id'], unique=False)
    op.create_table('paper_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('intent', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('size', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_reflections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('market_context', sa.Text(), nullable=True),
    sa.Column('price_change_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['workflow_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('prompt_template', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('exchange_order_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('strategies')
    op.drop_table('session_reflections')
    op.drop_table('paper_positions')
    op.drop_table('paper_orders')
    op.drop_index(op.f('ix_agent_logs_id'), table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_table('workflow_sessions')
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_table('signals')
    op.drop_table('paper_accounts')
    op.drop_index(op.f('ix_onchain_metrics_timestamp'), table_name='onchain_metrics')
    op.drop_index('idx_onchain_metric_time', table_name='onchain_metrics')
    op.drop_table('onchain_metrics')
    op.drop_table('news')
    op.drop_index(op.f('ix_macro_metrics_timestamp'), table_name='macro_metrics')
    op.drop_index('idx_macro_metric_time', table_name='macro_metrics')
    op.drop_table('macro_metrics')
    # ### end Alembic commands ###
