"""Add multitenant schema and automation rules

Revision ID: 499a4689c985
Revises: 20260320base
Create Date: 2026-07-26 11:15:56.683851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '499a4689c985'
down_revision: Union[str, None] = '20260320base'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('strategies')
    op.drop_index(op.f('idx_onchain_wallet_events_published_at'), table_name='onchain_wallet_events')
    op.drop_index(op.f('idx_onchain_wallet_events_source'), table_name='onchain_wallet_events')
    op.drop_table('onchain_wallet_events')
    op.drop_index(op.f('idx_llm_calibration_created_at'), table_name='llm_score_calibration_reports')
    op.drop_index(op.f('idx_llm_calibration_symbol_date'), table_name='llm_score_calibration_reports')
    op.drop_table('llm_score_calibration_reports')
    op.drop_index(op.f('idx_news_interp_asset_clusters_gin'), table_name='news_interpretations', postgresql_using='gin')
    op.drop_index(op.f('idx_news_interp_assets_gin'), table_name='news_interpretations', postgresql_using='gin')
    op.drop_index(op.f('idx_news_interp_factor_tags_gin'), table_name='news_interpretations', postgresql_using='gin')
    op.drop_index(op.f('idx_news_interp_final_status_time'), table_name='news_interpretations')
    op.drop_index(op.f('idx_news_interp_interpreted_at'), table_name='news_interpretations')
    op.drop_index(op.f('idx_news_interp_severity_time'), table_name='news_interpretations')
    op.drop_index(op.f('idx_news_interp_status_retry'), table_name='news_interpretations')
    op.drop_table('news_interpretations')
    op.alter_column('paper_accounts', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using="user_id::text::uuid")
    op.create_index(op.f('ix_paper_accounts_user_id'), 'paper_accounts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'paper_accounts', 'users', ['user_id'], ['id'])
    op.alter_column('paper_orders', 'intent',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'MARKET'::character varying"))
    op.add_column('workflow_sessions', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_workflow_sessions_user_id'), 'workflow_sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'workflow_sessions', 'users', ['user_id'], ['id'])
    op.drop_column('workflow_sessions', 'intent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_sessions', sa.Column('intent', sa.VARCHAR(length=20), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'workflow_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_workflow_sessions_user_id'), table_name='workflow_sessions')
    op.drop_column('workflow_sessions', 'user_id')
    op.alter_column('paper_orders', 'intent',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'MARKET'::character varying"))
    op.drop_constraint(None, 'paper_accounts', type_='foreignkey')
    op.drop_index(op.f('ix_paper_accounts_user_id'), table_name='paper_accounts')
    op.alter_column('paper_accounts', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_table('news_interpretations',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bias', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('magnitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('severity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_type_l1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_type_l2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary_cn', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assets', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('cross_market_impacts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('evidence_quotes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('final_status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('interpret_status', sa.TEXT(), server_default=sa.text("'NEW'::text"), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('next_retry_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('interpreted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('interpreter_version', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('content_fingerprint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fingerprint_algo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fingerprint_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reinterpret_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_reinterpret_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('asset_clusters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('factor_tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('impact_tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('mapping_version', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('noise_flags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('raw_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('language', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_tier', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('news_interpretations_pkey')),
    sa.UniqueConstraint('news_id', name=op.f('news_interpretations_news_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_news_interp_status_retry'), 'news_interpretations', ['interpret_status', 'next_retry_at'], unique=False)
    op.create_index(op.f('idx_news_interp_severity_time'), 'news_interpretations', ['severity', sa.literal_column('interpreted_at DESC')], unique=False)
    op.create_index(op.f('idx_news_interp_interpreted_at'), 'news_interpretations', [sa.literal_column('interpreted_at DESC')], unique=False)
    op.create_index(op.f('idx_news_interp_final_status_time'), 'news_interpretations', ['final_status', sa.literal_column('interpreted_at DESC')], unique=False)
    op.create_index(op.f('idx_news_interp_factor_tags_gin'), 'news_interpretations', ['factor_tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_news_interp_assets_gin'), 'news_interpretations', ['assets'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_news_interp_asset_clusters_gin'), 'news_interpretations', ['asset_clusters'], unique=False, postgresql_using='gin')
    op.create_table('llm_score_calibration_reports',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('run_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('window_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('methodology', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('execution_process', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('llm_score_calibration_reports_pkey')),
    sa.UniqueConstraint('run_date', 'symbol', name=op.f('llm_score_calibration_reports_run_date_symbol_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_llm_calibration_symbol_date'), 'llm_score_calibration_reports', ['symbol', sa.literal_column('run_date DESC')], unique=False)
    op.create_index(op.f('idx_llm_calibration_created_at'), 'llm_score_calibration_reports', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('onchain_wallet_events',
    sa.Column('event_uid', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_news_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('chain', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tx_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wallet_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('counterparty_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('direction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('asset_symbol', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amount_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_payload', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('event_uid', name=op.f('onchain_wallet_events_pkey'))
    )
    op.create_index(op.f('idx_onchain_wallet_events_source'), 'onchain_wallet_events', ['source'], unique=False)
    op.create_index(op.f('idx_onchain_wallet_events_published_at'), 'onchain_wallet_events', ['published_at'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('strategy_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('side', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exchange_order_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('orders_strategy_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
    )
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prompt_template', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('strategies_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('strategies_pkey'))
    )
    # ### end Alembic commands ###
