"use client";

import { SideNav } from "@/components/layout/SideNav";
import { AgentConfigEditor } from "@/components/strategy/AgentConfigEditor";
import { ConnectButton } from '@rainbow-me/rainbowkit';
import { BrainCircuit } from 'lucide-react';

export default function StrategyPage() {
  return (
    <div className="flex h-screen bg-[#020617] text-slate-200 overflow-hidden font-sans">
      
      {/* Sidebar */}
      <div className="w-[80px] min-w-[80px] border-r border-slate-800 bg-slate-900 flex flex-col items-center py-5 z-20">
         <SideNav />
      </div>
      
      {/* Main Content */}
      <main className="flex-1 flex flex-col overflow-hidden">
        
        {/* Header */}
        <header className="h-16 border-b border-slate-800 flex items-center justify-between px-8 bg-slate-900 shrink-0">
          <div className="flex items-center gap-3">
            <BrainCircuit className="text-blue-500" />
            <h1 className="font-bold text-lg text-white">Strategy Lab</h1>
            <span className="text-xs bg-blue-900/30 text-blue-400 px-2 py-0.5 rounded-full font-bold border border-blue-500/30">Experimental</span>
          </div>
          <div className="flex items-center gap-4">
            <ConnectButton />
          </div>
        </header>

        {/* Content Area */}
        <div className="flex-1 p-8 overflow-y-auto">
            <div className="max-w-5xl mx-auto">
                <div className="mb-8">
                    <h2 className="text-2xl font-bold text-white mb-2">Agent Configuration</h2>
                    <p className="text-slate-400">Customize the persona and decision-making logic of your AI agents. These settings directly influence the trading signals generated by the swarm.</p>
                </div>
                
                <AgentConfigEditor />
                
                <div className="mt-8 p-6 bg-slate-900 rounded-2xl border border-slate-800">
                    <h3 className="text-base font-bold text-white mb-4">Quick Tips</h3>
                    <ul className="list-disc pl-5 text-slate-400 space-y-2 text-sm leading-relaxed">
                        <li><strong className="text-blue-400">Analyst:</strong> Focus on which indicators (RSI, MACD) to prioritize.</li>
                        <li><strong className="text-purple-400">Strategist:</strong> Define your risk/reward ratio and preferred trade duration.</li>
                        <li><strong className="text-red-400">Reviewer:</strong> Set strict risk limits (Max Drawdown, Position Size).</li>
                    </ul>
                </div>
            </div>
        </div>

      </main>
    </div>
  );
}
